### ISSUE TITLE
不知道什么问题

### ISSUE THREAD

**Issue by yuanchenghao** [iceCola7/AndroidModuleSamples#2]
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by iceCola7** [comment]
我把代码下载下来，运行了一下，没出现这个问题啊。。难道是环境的问题吗

**Comment by yuanchenghao** [comment]
已经解决了 代码没问题
